<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>nyancat</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#labels</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#words</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#nums</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#sys_bits</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#bits</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#qubits</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#params</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments_block</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments_line</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.nyancat</string>
            <key>match</key>
            <string>\b(end|put|mov|cmp|je|jne|jg|jge|jl|jle|jmp|m|h|x|y|z)\b</string>
          </dict>
        </array>
      </dict>
      <key>labels</key>
      <dict>
        <key>name</key>
        <string>markup.bold.nyancat</string>
        <key>match</key>
        <string>[A-Z]([A-Za-z0-9_]*)\w*</string>
      </dict>
      <key>words</key>
      <dict>
        <key>name</key>
        <string>variable.name.nyancat</string>
        <key>match</key>
        <string>[a-z_]*([A-Za-z0-9_]*)\w+</string>
      </dict>
      <key>nums</key>
      <dict>
        <key>name</key>
        <string>variable.name.nyancat</string>
        <key>match</key>
        <string>[0-9]{1,}( |$)</string>
      </dict>
      <key>sys_bits</key>
      <dict>
        <key>name</key>
        <string>entity.name.function.nyancat</string>
        <key>match</key>
        <string>[0-9]{1,}%( |$)</string>
      </dict>
      <key>bits</key>
      <dict>
        <key>name</key>
        <string>constant.character.nyanct</string>
        <key>match</key>
        <string>[0-9]{1,}!( |$)</string>
      </dict>
      <key>qubits</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.nyancat</string>
        <key>match</key>
        <string>[0-9]{1,}\?( |$)</string>
      </dict>
      <key>params</key>
      <dict>
        <key>name</key>
        <string>variable.name.nyancat</string>
        <key>begin</key>
        <string>&lt;</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.language</string>
          </dict>
        </dict>
        <key>end</key>
        <string>&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.language</string>
          </dict>
        </dict>
      </dict>
      <key>comments_block</key>
      <dict>
        <key>name</key>
        <string>comment.block.nyancat</string>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
      </dict>
      <key>comments_line</key>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.nyancat</string>
        <key>match</key>
        <string>(//.*)</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.nyancat</string>
  </dict>
</plist>